spring.application.name=rally-order
server.port=8010
spring.profiles.active=dev

# DB
spring.datasource.url=jdbc:postgresql://localhost:5433/order_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway and Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-service
spring.kafka.consumer.auto-offset-reset=earliest

# Service Url
catalog.service.url=http://catalog-service:8082
inventory.service.url=http://inventory-service:8083

# Sweepers
sweeper.normal-order.reservation.fixed-delay-ms=2000
sweeper.normal-order.reservation.stale-after=20
sweeper.normal-order.reservation.batch-size=100

inventory.service.fake-delay-ms=30000
category.service.fake-delay-ms=30000